# https://www.w3schools.com/python/numpy/numpy_intro.asp

#What is NumPy?
# NumPy is a Python library used for working with arrays.
    
#Why Use NumPy?
# In Python we have lists that serve the purpose of arrays, but they are slow to process.
# NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
# The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

#Why is NumPy Faster Than Lists?
# NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.
# This behavior is called locality of reference in computer science.
# This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

#Getting started with numpy
https://www.w3schools.com/python/numpy/numpy_getting_started.asp

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(np.__version__) # To get the version


[1 2 3 4 5]
1.26.4


Creating Arrays

In [5]:
#Normal Arrays
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [7]:
#Check the dimensions of an array

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], 
			  [4, 5, 6]])
d = np.array([
			  [
			   [1, 2, 3],[4, 5, 6]
              ], 
               [
              	[1, 2, 3],[4, 5, 6]
               ]
              ])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
# For the 3D array, 123 is value at front, 456 values at back

0
1
2
3


Indexing 
# https://www.w3schools.com/python/numpy/numpy_array_indexing.asp

In [8]:
#How to get an element 
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [9]:
#Getting an elment in a 2D array [row, column]
import numpy as np
arr = np.array([
                [1,2,3,4,5], 
                [6,7,8,9,10]
               ])
print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [14]:
#Getting an element in a 3D array
import numpy as np
arr = np.array([
                [ [1, 2, 3],[4, 5, 6] ], #Array 0
                [ [7, 8, 9],[10, 11, 12] ] # Array 1
               ])
print(arr[0, 1, 2])

6


Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6

In [18]:
import numpy as np
arr = np.array([
              [1,2,3,4,5], # Array 0
              [6,7,8,9,10] # Array 1
             ])
print('Last element from 2nd dim: ', arr[1, -1]) # (Array 1, last value in array)

Last element from 2nd dim:  10


Slicing 

https://www.w3schools.com/python/numpy/numpy_array_slicing.asp
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step]

If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1

In [19]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])


[2 3 4 5]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [22]:
print(arr[:4])

[1 2 3 4]


In [25]:
#Specify range to print and gaps to count
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
print(arr[1:6:2])

[2 4]
[2 4 6]


In [ ]:
Data Types

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [26]:
#Get the data type of an array containing strings:
import numpy as np
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [27]:
#Creating Arrays With a Defined Data Type
import numpy as np
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [28]:
#Convert a current array by copying it
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Difference between copy and view 

Copy is a new array, and the view is just a view of the original array.
Copy owns the data and any changes made to the copy will not affect original array
Changes made to the original array will not affect the copy.

View does not own the data and any changes made to the view will affect the original array.
Any changes made to the original array will affect the view.

NumPy Array Copy vs View
#https://www.w3schools.com/python/numpy/numpy_copy_vs_view.asp

In [29]:
#Copy 
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [30]:
#View - make changes to original
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [31]:
#View - make changes to view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [1]:
#Check if Array Owns its Data
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


NumPy Array Shape
https://www.w3schools.com/python/numpy/numpy_array_shape.asp

In [2]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


Reshaping arrays

In [3]:
#Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Iterating Arrays

In [4]:
# https://www.w3schools.com/python/numpy/numpy_array_iterating.asp
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
NumPy Joining Array

In [5]:
#https://www.w3schools.com/python/numpy/numpy_array_join.asp
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [6]:
#Stacking Along Rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


NumPy Splitting Array

In [7]:
#Joining merges multiple arrays into one and Splitting breaks one array into multiple.

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
NumPy Searching Arrays

In [8]:
#search an array for a certain value, and return the indexes that get a match
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [9]:
#Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


NumPy Sorting Arrays

In [10]:
# Sorting means putting elements in an ordered sequence.
# Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [11]:
#Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


NumPy Filter Array

In [12]:
#https://www.w3schools.com/python/numpy/numpy_array_filter.asp

# Getting some elements out of an existing array and creating a new array out of them is called filtering.
# In NumPy, you filter an array using a boolean index list.

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

#Result
# If the value at an index is True that element is contained in the filtered array, 
# if the value at that index is False that element is excluded from the filtered array.
# The example above will return [41, 43], why?
# Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


In [13]:
#Create a filter array that will return only even elements from the original array:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [14]:
#Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]
